### ISSUE TITLE
processed data 

### ISSUE THREAD

**Issue by mzc2113391** [zhengdafangyuan/HiPore-C#8]
Hello,I can't open the processed data URL in paper "High-throughput Pore-C reveals the singleallele topology and cell type-specificity of 3D genome folding" (http://www.tgsbioinformatics.com/HiPore-C) 

How can I acquire the processed Pore-C data?（like .matrix file）?

Thanks a lot!!

**Comment by zhengdafangyuan** [comment]
Due to a cyber-attack last year, our management decided to shut down [www.tgsbioinformatics.com](http://www.tgsbioinformatics.com/) as a precaution, with an uncertain timeline for its return. However, we've ensured the availability of our processed data elsewhere: alignment data is accessible on GEO (accession number GSE202539), and we've uploaded contact matrix and methylation data to Zenodo (https://zenodo.org/records/10822184).
